# Generated by Django 3.2.8 on 2021-10-19 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('alias', models.CharField(max_length=200, null=True)),
                ('cid_location', models.IntegerField(null=True)),
                ('job_name', models.CharField(max_length=200, null=True)),
                ('cid_user', models.CharField(max_length=200, null=True)),
                ('cid_career', models.IntegerField(null=True)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('lat', models.CharField(max_length=200, null=True)),
                ('lng', models.CharField(max_length=200, null=True)),
                ('website', models.CharField(max_length=200, null=True)),
                ('social', models.TextField(max_length=200, null=True)),
                ('open_time', models.CharField(max_length=200, null=True)),
                ('close_time', models.CharField(max_length=200, null=True)),
                ('regular_holiday', models.TextField(max_length=200)),
                ('description', models.CharField(max_length=200, null=True)),
                ('contents', models.TextField(max_length=200, null=True)),
                ('google_map', models.CharField(max_length=200, null=True)),
                ('banner', models.CharField(max_length=200, null=True)),
                ('avatar_image', models.CharField(max_length=200, null=True)),
                ('images', models.TextField(max_length=100, null=True)),
                ('multi_images', models.TextField(max_length=100, null=True)),
                ('slider', models.TextField(max_length=100, null=True)),
                ('system', models.CharField(max_length=200, null=True)),
                ('hp', models.CharField(max_length=200, null=True)),
                ('ranking_host', models.SmallIntegerField(null=True)),
                ('pos_active', models.SmallIntegerField(null=True)),
                ('status', models.SmallIntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'hc_shop',
            },
        ),
    ]
