# Generated by Django 3.2.8 on 2021-10-19 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='cid_career',
            field=models.IntegerField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='cid_location',
            field=models.IntegerField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='pos_active',
            field=models.SmallIntegerField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='ranking_host',
            field=models.SmallIntegerField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='status',
            field=models.SmallIntegerField(max_length=200, null=True),
        ),
    ]
